name: 填报

on:
  push:
  schedule:
# 每天在国际标准时间22点（北京时间+8，即早上6点）运行
    - cron: '0 16 * * *'



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装Python下的requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: 填报
      env:
        LOGIN_ID: ${{secrets.LOGIN_ID}}
        LOGIN_PWD: ${{secrets.LOGIN_PWD}}
        HOUSEHOLD_REGISTER: ${{secrets.HOUSEHOLD_REGISTER}}
        PHONE_NUMBER: ${{secrets.PHONE_NUMBER}}
        CURRENT_LOCATION: ${{secrets.CURRENT_LOCATION}}
      run: |
        python tb.py
